using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using TMDbLib.Objects.Account;
using TMDbLib.Objects.Authentication;
using TMDbLib.Objects.Certifications;
using TMDbLib.Objects.Changes;
using TMDbLib.Objects.Collections;
using TMDbLib.Objects.Companies;
using TMDbLib.Objects.Credit;
using TMDbLib.Objects.Discover;
using TMDbLib.Objects.Find;
using TMDbLib.Objects.General;
using TMDbLib.Objects.Lists;
using TMDbLib.Objects.Movies;
using TMDbLib.Objects.People;
using TMDbLib.Objects.Reviews;
using TMDbLib.Objects.Search;
using TMDbLib.Objects.Timezones;
using TMDbLib.Objects.TvShows;
using Credits = TMDbLib.Objects.Movies.Credits;

namespace Octogami.SixDegreesOfNetflix.Application.TMDB
{
    // ReSharper disable once InconsistentNaming
    public interface ITMDbClient
    {
        Uri GetImageUrl(string size, string filePath, bool useSsl);
        Task<bool> AccountChangeFavoriteStatusAsync(MediaType mediaType, int mediaId, bool isFavorite);
        Task<bool> AccountChangeWatchlistStatusAsync(MediaType mediaType, int mediaId, bool isOnWatchlist);
        Task<AccountDetails> AccountGetDetailsAsync();
        Task<SearchContainer<SearchMovie>> AccountGetFavoriteMoviesAsync(int page, AccountSortBy sortBy, SortOrder sortOrder, string language);
        Task<SearchContainer<SearchTv>> AccountGetFavoriteTvAsync(int page, AccountSortBy sortBy, SortOrder sortOrder, string language);
        Task<SearchContainer<AccountList>> AccountGetListsAsync(int page, string language);
        Task<SearchContainer<SearchMovie>> AccountGetMovieWatchlistAsync(int page, AccountSortBy sortBy, SortOrder sortOrder, string language);
        Task<SearchContainer<SearchMovieWithRating>> AccountGetRatedMoviesAsync(int page, AccountSortBy sortBy, SortOrder sortOrder, string language);
        Task<SearchContainer<AccountSearchTvEpisode>> AccountGetRatedTvShowEpisodesAsync(int page, AccountSortBy sortBy, SortOrder sortOrder, string language);
        Task<SearchContainer<AccountSearchTv>> AccountGetRatedTvShowsAsync(int page, AccountSortBy sortBy, SortOrder sortOrder, string language);
        Task<SearchContainer<SearchTv>> AccountGetTvWatchlistAsync(int page, AccountSortBy sortBy, SortOrder sortOrder, string language);
        Task<GuestSession> AuthenticationCreateGuestSessionAsync();
        Task<UserSession> AuthenticationGetUserSessionAsync(string initialRequestToken);
        Task<UserSession> AuthenticationGetUserSessionAsync(string username, string password);
        Task<Token> AuthenticationRequestAutenticationTokenAsync();
        Task AuthenticationValidateUserTokenAsync(string initialRequestToken, string username, string password);
        Task<CertificationsContainer> GetMovieCertificationsAsync();
        Task<CertificationsContainer> GetTvCertificationsAsync();
        Task<SearchContainer<ChangesListItem>> GetChangesMoviesAsync(int page, DateTime? startDate, DateTime? endDate);
        Task<SearchContainer<ChangesListItem>> GetChangesPeopleAsync(int page, DateTime? startDate, DateTime? endDate);
        Task<SearchContainer<ChangesListItem>> GetChangesTvAsync(int page, DateTime? startDate, DateTime? endDate);
        Task<Collection> GetCollectionAsync(int collectionId, CollectionMethods extraMethods);
        Task<Collection> GetCollectionAsync(int collectionId, string language, CollectionMethods extraMethods);
        Task<ImagesWithId> GetCollectionImagesAsync(int collectionId, string language);
        Task<Company> GetCompanyAsync(int companyId, CompanyMethods extraMethods);
        Task<SearchContainerWithId<SearchMovie>> GetCompanyMoviesAsync(int companyId, int page);
        Task<SearchContainerWithId<SearchMovie>> GetCompanyMoviesAsync(int companyId, string language, int page);
        Task<Credit> GetCreditsAsync(string id);
        Task<Credit> GetCreditsAsync(string id, string language);
        DiscoverMovie DiscoverMoviesAsync();
        DiscoverTv DiscoverTvShowsAsync();
        Task<FindContainer> FindAsync(FindExternalSource source, string id);
        Task<SearchContainerWithId<SearchMovie>> GetGenreMoviesAsync(int genreId, int page, bool? includeAllMovies);
        Task<SearchContainerWithId<SearchMovie>> GetGenreMoviesAsync(int genreId, string language, int page, bool? includeAllMovies);
        Task<List<Genre>> GetMovieGenresAsync();
        Task<List<Genre>> GetMovieGenresAsync(string language);
        Task<List<Genre>> GetTvGenresAsync();
        Task<List<Genre>> GetTvGenresAsync(string language);
        Task<SearchContainer<SearchMovieWithRating>> GetGuestSessionRatedMoviesAsync(int page);
        Task<SearchContainer<SearchMovieWithRating>> GetGuestSessionRatedMoviesAsync(string language, int page);
        Task<SearchContainer<SearchTvShowWithRating>> GetGuestSessionRatedTvAsync(int page);
        Task<SearchContainer<SearchTvShowWithRating>> GetGuestSessionRatedTvAsync(string language, int page);
        Task<SearchContainer<TvEpisodeWithRating>> GetGuestSessionRatedTvEpisodesAsync(int page);
        Task<SearchContainer<TvEpisodeWithRating>> GetGuestSessionRatedTvEpisodesAsync(string language, int page);
        Task<List<Job>> GetJobsAsync();
        Task<Keyword> GetKeywordAsync(int keywordId);
        Task<SearchContainerWithId<SearchMovie>> GetKeywordMoviesAsync(int keywordId, int page);
        Task<SearchContainerWithId<SearchMovie>> GetKeywordMoviesAsync(int keywordId, string language, int page);
        Task<GenericList> GetListAsync(string listId);
        Task<bool> GetListIsMoviePresentAsync(string listId, int movieId);
        Task<bool> ListAddMovieAsync(string listId, int movieId);
        Task<bool> ListClearAsync(string listId);
        Task<string> ListCreateAsync(string name, string description, string language);
        Task<bool> ListDeleteAsync(string listId);
        Task<bool> ListRemoveMovieAsync(string listId, int movieId);
        Task<AccountState> GetMovieAccountStateAsync(int movieId);
        Task<AlternativeTitles> GetMovieAlternativeTitlesAsync(int movieId);
        Task<AlternativeTitles> GetMovieAlternativeTitlesAsync(int movieId, string country);
        Task<Movie> GetMovieAsync(int movieId, MovieMethods extraMethods);
        Task<Movie> GetMovieAsync(string imdbId, MovieMethods extraMethods);
        Task<Movie> GetMovieAsync(int movieId, string language, MovieMethods extraMethods);
        Task<Movie> GetMovieAsync(string imdbId, string language, MovieMethods extraMethods);
        Task<List<Change>> GetMovieChangesAsync(int movieId, DateTime? startDate, DateTime? endDate);
        Task<Credits> GetMovieCreditsAsync(int movieId);
        Task<ImagesWithId> GetMovieImagesAsync(int movieId);
        Task<ImagesWithId> GetMovieImagesAsync(int movieId, string language);
        Task<KeywordsContainer> GetMovieKeywordsAsync(int movieId);
        Task<Movie> GetMovieLatestAsync();
        Task<SearchContainerWithId<ListResult>> GetMovieListsAsync(int movieId, int page);
        Task<SearchContainerWithId<ListResult>> GetMovieListsAsync(int movieId, string language, int page);
        Task<SearchContainer<SearchMovie>> GetMovieRecommendationsAsync(int id, int page);
        Task<SearchContainer<SearchMovie>> GetMovieRecommendationsAsync(int id, string language, int page);
        Task<SearchContainerWithDates<SearchMovie>> GetMovieNowPlayingListAsync(string language, int page);
        Task<SearchContainer<SearchMovie>> GetMoviePopularListAsync(string language, int page);
        Task<ResultContainer<ReleaseDatesContainer>> GetMovieReleaseDatesAsync(int movieId);
        Task<Releases> GetMovieReleasesAsync(int movieId);
        Task<SearchContainerWithId<ReviewBase>> GetMovieReviewsAsync(int movieId, int page);
        Task<SearchContainerWithId<ReviewBase>> GetMovieReviewsAsync(int movieId, string language, int page);
        Task<SearchContainer<SearchMovie>> GetMovieSimilarAsync(int movieId, int page);
        Task<SearchContainer<SearchMovie>> GetMovieSimilarAsync(int movieId, string language, int page);
        Task<SearchContainer<SearchMovie>> GetMovieTopRatedListAsync(string language, int page);
        Task<TranslationsContainer> GetMovieTranslationsAsync(int movieId);
        Task<SearchContainerWithDates<SearchMovie>> GetMovieUpcomingListAsync(string language, int page);
        Task<ResultContainer<Video>> GetMovieVideosAsync(int movieId);
        Task<bool> MovieRemoveRatingAsync(int movieId);
        Task<bool> MovieSetRatingAsync(int movieId, double rating);
        Task<Network> GetNetworkAsync(int networkId);
        Task<Person> GetLatestPersonAsync();
        Task<Person> GetPersonAsync(int personId, PersonMethods extraMethods);
        Task<List<Change>> GetPersonChangesAsync(int personId, DateTime? startDate, DateTime? endDate);
        Task<ExternalIdsPerson> GetPersonExternalIdsAsync(int personId);
        Task<ProfileImages> GetPersonImagesAsync(int personId);
        Task<SearchContainer<PersonResult>> GetPersonListAsync(PersonListType type, int page);
        Task<MovieCredits> GetPersonMovieCreditsAsync(int personId);
        Task<MovieCredits> GetPersonMovieCreditsAsync(int personId, string language);
        Task<SearchContainerWithId<TaggedImage>> GetPersonTaggedImagesAsync(int personId, int page);
        Task<SearchContainerWithId<TaggedImage>> GetPersonTaggedImagesAsync(int personId, string language, int page);
        Task<TvCredits> GetPersonTvCreditsAsync(int personId);
        Task<TvCredits> GetPersonTvCreditsAsync(int personId, string language);
        Task<Review> GetReviewAsync(string reviewId);
        Task<SearchContainer<SearchCollection>> SearchCollectionAsync(string query, int page);
        Task<SearchContainer<SearchCollection>> SearchCollectionAsync(string query, string language, int page);
        Task<SearchContainer<SearchCompany>> SearchCompanyAsync(string query, int page);
        Task<SearchContainer<SearchKeyword>> SearchKeywordAsync(string query, int page);
        Task<SearchContainer<SearchList>> SearchListAsync(string query, int page, bool includeAdult);
        Task<SearchContainer<SearchMovie>> SearchMovieAsync(string query, int page, bool includeAdult, int year);
        Task<SearchContainer<SearchMovie>> SearchMovieAsync(string query, string language, int page, bool includeAdult, int year);
        Task<SearchContainer<SearchBase>> SearchMultiAsync(string query, int page, bool includeAdult, int year);
        Task<SearchContainer<SearchBase>> SearchMultiAsync(string query, string language, int page, bool includeAdult, int year);
        Task<SearchContainer<SearchPerson>> SearchPersonAsync(string query, int page, bool includeAdult);
        Task<SearchContainer<SearchTv>> SearchTvShowAsync(string query, int page);
        Task<Timezones> GetTimezonesAsync();
        Task<TvEpisodeAccountState> GetTvEpisodeAccountStateAsync(int tvShowId, int seasonNumber, int episodeNumber);
        Task<TvEpisode> GetTvEpisodeAsync(int tvShowId, int seasonNumber, int episodeNumber, TvEpisodeMethods extraMethods, string language);
        Task<ChangesContainer> GetTvEpisodeChangesAsync(int episodeId);
        Task<CreditsWithGuestStars> GetTvEpisodeCreditsAsync(int tvShowId, int seasonNumber, int episodeNumber, string language);
        Task<ExternalIdsTvEpisode> GetTvEpisodeExternalIdsAsync(int tvShowId, int seasonNumber, int episodeNumber);
        Task<StillImages> GetTvEpisodeImagesAsync(int tvShowId, int seasonNumber, int episodeNumber, string language);
        Task<ResultContainer<Video>> GetTvEpisodeVideosAsync(int tvShowId, int seasonNumber, int episodeNumber);
        Task<bool> TvEpisodeRemoveRatingAsync(int tvShowId, int seasonNumber, int episodeNumber);
        Task<bool> TvEpisodeSetRatingAsync(int tvShowId, int seasonNumber, int episodeNumber, double rating);
        Task<ResultContainer<TvEpisodeAccountStateWithNumber>> GetTvSeasonAccountStateAsync(int tvShowId, int seasonNumber);
        Task<TvSeason> GetTvSeasonAsync(int tvShowId, int seasonNumber, TvSeasonMethods extraMethods, string language);
        Task<ChangesContainer> GetTvSeasonChangesAsync(int seasonId);
        Task<TMDbLib.Objects.TvShows.Credits> GetTvSeasonCreditsAsync(int tvShowId, int seasonNumber, string language);
        Task<ExternalIdsTvSeason> GetTvSeasonExternalIdsAsync(int tvShowId, int seasonNumber);
        Task<PosterImages> GetTvSeasonImagesAsync(int tvShowId, int seasonNumber, string language);
        Task<ResultContainer<Video>> GetTvSeasonVideosAsync(int tvShowId, int seasonNumber, string language);
        Task<TvShow> GetLatestTvShowAsync();
        Task<AccountState> GetTvShowAccountStateAsync(int tvShowId);
        Task<ResultContainer<AlternativeTitle>> GetTvShowAlternativeTitlesAsync(int id);
        Task<TvShow> GetTvShowAsync(int id, TvShowMethods extraMethods, string language);
        Task<ChangesContainer> GetTvShowChangesAsync(int id);
        Task<ResultContainer<ContentRating>> GetTvShowContentRatingsAsync(int id);
        Task<TMDbLib.Objects.TvShows.Credits> GetTvShowCreditsAsync(int id, string language);
        Task<ExternalIdsTvShow> GetTvShowExternalIdsAsync(int id);
        Task<ImagesWithId> GetTvShowImagesAsync(int id, string language);
        Task<ResultContainer<Keyword>> GetTvShowKeywordsAsync(int id);
        Task<SearchContainer<SearchTv>> GetTvShowListAsync(TvShowListType list, int page, string timezone);
        Task<SearchContainer<SearchTv>> GetTvShowListAsync(TvShowListType list, string language, int page, string timezone);
        Task<SearchContainer<SearchTv>> GetTvShowPopularAsync(int page, string language);
        Task<SearchContainer<SearchTv>> GetTvShowSimilarAsync(int id, int page);
        Task<SearchContainer<SearchTv>> GetTvShowSimilarAsync(int id, string language, int page);
        Task<SearchContainer<SearchTv>> GetTvShowRecommendationsAsync(int id, int page);
        Task<SearchContainer<SearchTv>> GetTvShowRecommendationsAsync(int id, string language, int page);

        Task<SearchContainer<SearchTv>> GetTvShowTopRatedAsync(int page, string language);
        Task<TranslationsContainerTv> GetTvShowTranslationsAsync(int id);
        Task<ResultContainer<Video>> GetTvShowVideosAsync(int id);
        Task<bool> TvShowRemoveRatingAsync(int tvShowId);
        Task<bool> TvShowSetRatingAsync(int tvShowId, double rating);
        AccountDetails ActiveAccount { get; }
        string ApiKey { get; }
    }
}